dino_input_size: 518
f_x: 554.25
f_y: 554.25
lambda_: 0.5
max_error: 100.0
max_iterations: 1000
max_velocity: 1.0
min_error: 5.0
min_iterations: 50
num_pairs: 10
u_max: 640
v_max: 480
velocity_convergence_threshold: 0.1
